services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: shopuser
      POSTGRES_PASSWORD: shoppass
      POSTGRES_DB: shopdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shopdb
      DB_USER: shopuser
      DB_PASS: shoppass
    ports:
      - "18080:8080"
      - "18081:8081"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
